@AcmeDealership_HostAddress = http://localhost:5096

### AcmeDealership Customer API Tests

### Get all customers
GET {{AcmeDealership_HostAddress}}/api/customers
Accept: application/json

###

### Get customer by ID (replace with actual ID from your data)
GET {{AcmeDealership_HostAddress}}/api/customers/541d25c9-9500-4265-8967-240f44ecf723
Accept: application/json

###

### Get customer recommendations for NYC location
POST {{AcmeDealership_HostAddress}}/api/customers/recommendations
Content-Type: application/json

{
  "latitude": 40.7128,
  "longitude": -74.0060,
  "count": 10
}

###

### Get customer recommendations for Los Angeles location
POST {{AcmeDealership_HostAddress}}/api/customers/recommendations
Content-Type: application/json

{
  "latitude": 34.0522,
  "longitude": -118.2437,
  "count": 5
}

###

### Get customers by age range
GET {{AcmeDealership_HostAddress}}/api/customers/age-range?minAge=25&maxAge=45
Accept: application/json

###

### Get customer statistics
GET {{AcmeDealership_HostAddress}}/api/customers/statistics
Accept: application/json

###

### Export customers (binary serialization)
POST {{AcmeDealership_HostAddress}}/api/customers/export
Accept: application/json

###

### Export specific customer (binary serialization)
POST {{AcmeDealership_HostAddress}}/api/customers/export?customerId=541d25c9-9500-4265-8967-240f44ecf723
Accept: application/json

###

### Test error handling - Invalid customer ID
GET {{AcmeDealership_HostAddress}}/api/customers/invalid-id
Accept: application/json

###

### Test validation - Invalid latitude
POST {{AcmeDealership_HostAddress}}/api/customers/recommendations
Content-Type: application/json

{
  "latitude": 999,
  "longitude": -74.0060,
  "count": 10
}

###

### Test validation - Invalid count
POST {{AcmeDealership_HostAddress}}/api/customers/recommendations
Content-Type: application/json

{
  "latitude": 40.7128,
  "longitude": -74.0060,
  "count": 100
}

###

### Create new customer
POST {{AcmeDealership_HostAddress}}/api/customers
Content-Type: application/json

{
  "id": "test-customer-123",
  "name": "Test Customer",
  "age": 30,
  "location": {
    "latitude": 40.7589,
    "longitude": -73.9851
  },
  "acceptedOffers": 5,
  "canceledOffers": 2,
  "averageReplyTime": 1500
}

###

### Update customer
PUT {{AcmeDealership_HostAddress}}/api/customers/test-customer-123
Content-Type: application/json

{
  "id": "test-customer-123",
  "name": "Updated Test Customer",
  "age": 31,
  "location": {
    "latitude": 40.7589,
    "longitude": -73.9851
  },
  "acceptedOffers": 6,
  "canceledOffers": 2,
  "averageReplyTime": 1200
}

###

### Delete customer
DELETE {{AcmeDealership_HostAddress}}/api/customers/test-customer-123
Accept: application/json
